//
//  AndroidSheet.swift
//  AndroidSwiftUI
//
//  Created by Alsey Coleman Miller on 7/21/26.
//

import AndroidKit

extension _SheetPresenter: AndroidPrimitive {

    var renderedBody: AnyView {
        AnyView(AndroidSheetContainer(presenter: self))
    }
}

/// Native container for `.sheet(isPresented:onDismiss:content:)`.
///
/// The sheet is rendered as an overlay rather than an Android `Dialog`: the fiber renderer mounts
/// children by adding them to their parent `ViewGroup`, so the presented content has to live in the
/// same view hierarchy as the presenting content. `BackHandlerView` is a `FrameLayout`, so the sheet
/// content is stacked on top of the host content and the system back button is intercepted while the
/// sheet is presented.
struct AndroidSheetContainer<Content: View> {

    let presenter: _SheetPresenter<Content>
}

extension AndroidSheetContainer: ParentView {

    var children: [AnyView] {
        var views = [AnyView(presenter.content)]
        if presenter.isSheetPresented {
            let presenter = self.presenter
            let content = presenter.sheetContent()
            let detents = mapAnyView(content, transform: { (view: _AnyPresentationDetentsView) in view })?
                .detents ?? []
            if !detents.isEmpty {
                // dim and block interaction with the presenting content behind a partial sheet
                views.append(AnyView(AndroidSheetScrim()))
            }
            let sheet = AndroidSheetOverlay(content: content, detents: detents)
                .environment(\.dismiss, DismissAction { presenter.dismiss() })
                .environment(\.isPresented, true)
            views.append(AnyView(sheet))
        }
        return views
    }
}

extension AndroidSheetContainer: AndroidViewRepresentable {

    typealias Coordinator = Void

    func makeAndroidView(context: Self.Context) -> BackHandlerView {
        let presenter = self.presenter
        let view = BackHandlerView(context.androidContext) {
            presenter.dismiss()
        }
        updateView(view)
        return view
    }

    func updateAndroidView(_ view: BackHandlerView, context: Self.Context) {
        updateView(view)
    }
}

private extension AndroidSheetContainer {

    func updateView(_ view: BackHandlerView) {
        // only intercept the back button while the sheet is on screen
        view.setBackHandlerEnabled(presenter.isSheetPresented)
    }
}

/// Opaque, full size container for the presented sheet content, stacked above the presenting content.
///
/// When detents are provided, the container is instead anchored to the bottom of the screen at
/// the height of the smallest detent.
struct AndroidSheetOverlay {

    let content: AnyView

    var detents: Set<PresentationDetent> = []
}

extension AndroidSheetOverlay: ParentView {

    var children: [AnyView] {
        [content]
    }
}

extension AndroidSheetOverlay: AndroidViewRepresentable {

    typealias Coordinator = Void

    func makeAndroidView(context: Self.Context) -> AndroidWidget.FrameLayout {
        let androidContext = context.androidContext
        let view = AndroidWidget.FrameLayout(androidContext)
        applyLayoutParams(to: view, context: androidContext)
        view.setBackgroundColor(Self.backgroundColor(androidContext))
        // swallow touches so the presenting content underneath is not interactive
        view.setClickable(true)
        view.setFocusable(true)
        // draw above the presenting content
        view.setElevation(16)
        view.bringToFront()
        return view
    }

    func updateAndroidView(_ view: AndroidWidget.FrameLayout, context: Self.Context) {
        applyLayoutParams(to: view, context: context.androidContext)
        view.bringToFront()
    }
}

private extension AndroidSheetOverlay {

    func applyLayoutParams(to view: AndroidWidget.FrameLayout, context: AndroidContent.Context) {
        let matchParent = try! JavaClass<ViewGroup.LayoutParams>().MATCH_PARENT
        let height = smallestDetentHeight(context)
        // once attached, mutate the existing parameters so the subclass generated by the
        // parent is preserved; replacing them with base `ViewGroup.LayoutParams` crashes
        // the parent's measure pass, which expects margin parameters
        if let params = view.getLayoutParams() {
            params.width = matchParent
            params.height = height ?? matchParent
            if height != nil, let frameParams = params.as(AndroidWidget.FrameLayout.LayoutParams.self) {
                // anchor a partial height sheet to the bottom of the screen
                frameParams.gravity = ViewGravity.bottom.rawValue
            }
            view.setLayoutParams(params)
        } else if let height {
            let params = AndroidWidget.FrameLayout.LayoutParams(matchParent, height, ViewGravity.bottom.rawValue)
            view.setLayoutParams(params.as(ViewGroup.LayoutParams.self))
        } else {
            let params = AndroidWidget.FrameLayout.LayoutParams(matchParent, matchParent)
            view.setLayoutParams(params.as(ViewGroup.LayoutParams.self))
        }
    }

    /// The pixel height of the smallest detent, or `nil` for a full size sheet.
    func smallestDetentHeight(_ context: AndroidContent.Context) -> Int32? {
        guard detents.isEmpty == false,
              let metrics = context.getResources()?.getDisplayMetrics()
        else { return nil }
        let screenHeight = Float(metrics.heightPixels)
        let pixelHeights = detents.map { detent -> Float in
            switch detent.storage {
            case .medium:
                return screenHeight * 0.5
            case .large:
                return screenHeight
            case let .fraction(fraction):
                return screenHeight * Float(fraction)
            case let .height(height):
                return Float(height) * metrics.density
            }
        }
        guard let smallest = pixelHeights.min(), smallest < screenHeight else {
            return nil
        }
        return Int32(smallest.rounded())
    }

    /// The theme's window background, so the sheet is opaque in both light and dark themes.
    static func backgroundColor(_ context: AndroidContent.Context) -> Int32 {
        let opaqueWhite = Int32(bitPattern: 0xFF_FF_FF_FF)
        guard let theme = context.getTheme() else {
            return opaqueWhite
        }
        let value = AndroidUtil.TypedValue()
        let attribute = try! JavaClass<AndroidR.R.attr>().colorBackground
        guard theme.resolveAttribute(attribute, value, true) else {
            return opaqueWhite
        }
        return value.data
    }
}

/// Dimmed, non-interactive backdrop shown behind a partial height sheet.
struct AndroidSheetScrim { }

extension AndroidSheetScrim: AndroidViewRepresentable {

    typealias Coordinator = Void

    func makeAndroidView(context: Self.Context) -> AndroidView.View {
        let view = AndroidView.View(context.androidContext)
        let matchParent = try! JavaClass<ViewGroup.LayoutParams>().MATCH_PARENT
        view.setLayoutParams(ViewGroup.LayoutParams(matchParent, matchParent))
        // 40% black dim, matching the system bottom sheet scrim
        view.setBackgroundColor(Int32(bitPattern: 0x66_00_00_00))
        // swallow touches so the presenting content underneath is not interactive
        view.setClickable(true)
        view.setFocusable(true)
        // draw above the presenting content, below the sheet
        view.setElevation(15)
        return view
    }

    func updateAndroidView(_ view: AndroidView.View, context: Self.Context) { }
}
